List<Map<String, dynamic>> luxuryCars = [
  {
    'id': 1,
    'name': 'Rolls-Royce Phantom',
    'rating': 4.8,
    'pricePerHour': 500.0,
    'pricePerDay': 3000.0,
    'description': 'The ultimate luxury sedan.',
    'engine': 'V12',
    'wheelbase': 3570.0,
    'reviews':"28 reviews",
    'model': '2022',
    'image2':"https://th.bing.com/th/id/OIP.TPKQtUFTxfOqjG3VXwuSMgHaE8?rs=1&pid=ImgDetMain",
    'image1':"https://th.bing.com/th/id/OIP.mGxhS0_qC_W47SSAwTpPbgHaE7?w=1280&h=853&rs=1&pid=ImgDetMain",
    'image': 'https://th.bing.com/th/id/OIP.TPKQtUFTxfOqjG3VXwuSMgHaE8?rs=1&pid=ImgDetMain',
  },
  {
    'id': 2,
    'name': 'Bentley Continental GT',
    'rating': 4.7,
    'pricePerHour': 400.0,
    'reviews':"40 reviews",
    'pricePerDay': 2500.0,
    'description': 'A blend of luxury and performance.',
    'engine': 'W12',
    'wheelbase': 2851.0,
    'model': '2024',
    'image1':"https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg__marking_background__sm_/v1/editorial/2019-Bentley-Continental-V8-GT-coupe-orange-press-image-1001x565p-(1).jpg",
    'image2':"https://th.bing.com/th/id/OIP.D6Q5v8mz4Pvxn9k4yw3mXgHaED?rs=1&pid=ImgDetMain",
    'image': 'https://th.bing.com/th/id/OIP.sN5ar3BekSkGtMccVvzUuwHaEK?w=1920&h=1080&rs=1&pid=ImgDetMain',
  },
  {
    'id': 3,
    'name': 'Mercedes-Maybach S-Class',
    'rating': 4.6,
    'pricePerHour': 450.0,
    'pricePerDay': 2800.0,
    'description': 'Unparalleled comfort and sophistication.',
    'engine': 'V8',
    'reviews':"10 reviews",
    'wheelbase': 3365.0,
    'model': '2021',
    'image1':"https://carwow-uk-wp-2.imgix.net/maybach-s-class-parked-front-2.jpg?auto=format&cs=tinysrgb&fit=clip&ixlib=rb-1.1.0&q=60&w=1920",
    'image2':"https://autonxt.net/wp-content/uploads/2020/11/2021_Mercedes-Maybach_S_580_4MATIC_1-1024x614.jpg",
    'image': "https://th.bing.com/th/id/OIP.4CrtHUCOCeLIzV1TKQezvwAAAA?rs=1&pid=ImgDetMain"
  },
  {
    'id': 4,
    'name': 'Lamborghini Urus',
    'rating': 4.9,
    'pricePerHour': 550.0,
    'pricePerDay': 3500.0,
    'description': 'The world\'s first Super Sport Utility Vehicle.',
    'engine': 'V8 twin-turbo',
    'wheelbase': 3003.0,
    'model': '2023',
    'reviews':"35 reviews",
    'image2':"https://td-luxe.com/wp-content/uploads/2019/12/Ext4-2-scaled.jpg",
    'image1':"https://td-luxe.com/wp-content/uploads/2019/12/Ext3-5-scaled.jpg",
    'image': 'https://td-luxe.com/wp-content/uploads/2019/12/Ext1-4-scaled.jpg',
  },
  {
    'id': 5,
    'name': 'Ferrari SF90 Stradale',
    'rating': 4.8,
    'pricePerHour': 600.0,
    'pricePerDay': 3800.0,
    'reviews':"64 reviews",
    'description': 'The ultimate expression of Ferrari\'s extreme sports car technology.',
    'engine': 'V8 twin-turbo hybrid',
    'wheelbase': 2650.0,
    'model': '2022',
    'image2':"https://www.carscoops.com/wp-content/uploads/2022/08/Ferrari-SF90-Stradale-6-1-768x512.jpg",
    'image1':"https://www.vipcarrental.ae/wp-content/uploads/2023/07/Ferrari-SF-90-3-optimized.webp",
    'image': 'https://www.carscoops.com/wp-content/uploads/2022/08/Ferrari-SF90-Stradale-5a-1024x555.jpg',
  },
];
